// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model




// User is the golang structure for table user.
type User struct {
    Id       uint64 `orm:"id,primary" json:"id"       description:""`                  //                    
    Name     string `orm:"name"       json:"name"     description:"user name"`         // user name          
    Nick     string `orm:"nick"       json:"nick"     description:"user nickname"`     // user nickname      
    Password string `orm:"password"   json:"password" description:"user password"`     // user password      
    Email    string `orm:"email"      json:"email"    description:"user email"`        // user email         
    Age      uint   `orm:"age"        json:"age"      description:"user age"`          // user age           
    HeadImg  string `orm:"head_img"   json:"headImg"  description:"user head img url"` // user head img url  
}