// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/smokecat/gfdemo/app/dao/internal"
)

// equipmentDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type equipmentDao struct {
	*internal.EquipmentDao
}

var (
	// Equipment is globally public accessible object for table equipment operations.
	Equipment = equipmentDao{
		internal.NewEquipmentDao(),
	}
)

// Fill with you ideas below.